# Site settings
baseurl = "https://Cody2333.github.io/blog/"
languageCode = "en"
title = "Coooody's"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

[params]
	author = "coooody"
	description = "科科"
	bio = "Look, Look at the sky now, what color is it? "

	twitter = "your_twitter_id"
	facebook = "your_facebook_id"

	enableRSS = false
	enableToc = true

	enableDisqus = false
	disqusShortname = "your_disqus_short_name"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = false
	enableBaiduAnalytics = true
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = '''<script>
		var _hmt = _hmt || [];
		(function() {
			var hm = document.createElement("script");
			hm.src = "https://hm.baidu.com/hm.js?27f84b75a4ae3ba1b7b21d996fdf549c";
			var s = document.getElementsByTagName("script")[0]; 
			s.parentNode.insertBefore(hm, s);
		})();
		</script>
		'''

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = true
	readMore = true

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/cody.wang.585"
	github-square = "https://www.github.com/Cody2333"
	home = "https://cody.wang"
